# Generated by Django 5.2.4 on 2025-10-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_blocked_until_customuser_is_blocked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_blocked",
        ),
        migrations.AddField(
            model_name="customuser",
            name="failed_attempts",
            field=models.SmallIntegerField(default=0),
        ),
    ]
