# Generated by Django 5.2.4 on 2026-01-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_cart_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
