# Generated by Django 5.2.4 on 2026-01-20 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_cart_quantity"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="likedproduct",
            unique_together={("user", "product")},
        ),
    ]
