# Generated by Django 5.2.4 on 2026-01-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_likedproduct_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("name", "price", "category", "retailer")},
        ),
    ]
