# Generated by Django 5.2.4 on 2026-01-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_review_comment_alter_product_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
