# Generated by Django 5.2.4 on 2026-01-25 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_alter_cart_unique_together_cart_unique_cart_item_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cart",
            name="quantity_at_least_one",
        ),
    ]
