# Generated by Django 5.2.4 on 2026-01-25 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_remove_cart_quantity_at_least_one"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cart",
            name="unique_cart_item",
        ),
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together={("user", "product")},
        ),
    ]
