# Generated by Django 5.2.4 on 2026-01-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_remove_cart_unique_cart_item_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                fields=("user", "product"), name="unique_cart_item"
            ),
        ),
    ]
