# Generated by Django 5.2.4 on 2026-01-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_alter_cart_unique_together_cart_unique_cart_item"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)), name="quantity_at_least_one"
            ),
        ),
    ]
