# Generated by Django 5.2.4 on 2026-01-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_cart_quantity_at_least_one"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
