# Generated by Django 5.2.4 on 2026-01-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_alter_cart_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_purchased",
            field=models.BooleanField(default=False),
        ),
    ]
