# Generated by Django 5.2.4 on 2026-01-25 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0018_order_is_purchased"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_purchased",
        ),
    ]
