# Generated by Django 5.2.4 on 2026-01-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0019_remove_order_is_purchased"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
