# Generated by Django 5.2.4 on 2026-02-04 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0021_address_order_shipping_address"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cart",
            name="unique_cart_item",
        ),
    ]
