# Generated by Django 5.2.4 on 2025-11-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_alter_attendance_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
