# Generated by Django 5.2.4 on 2025-11-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_employee_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="photo",
        ),
    ]
