# Generated by Django 5.2.4 on 2025-11-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IpCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("first_request_time", models.DateTimeField(auto_now_add=True)),
                ("last_request_time", models.DateTimeField(auto_now=True)),
                ("tokens_count", models.IntegerField(default=10)),
                ("tokens_spent", models.IntegerField(default=0)),
            ],
        ),
    ]
