# Generated by Django 5.2.4 on 2025-11-26 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_middleware", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ipcount",
            name="tokens_count",
        ),
    ]
