# Generated by Django 5.2.4 on 2025-11-27 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_middleware", "0002_remove_ipcount_tokens_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ipcount",
            name="last_request_time",
        ),
    ]
