# Generated by Django 5.2.4 on 2025-11-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_middleware", "0003_remove_ipcount_last_request_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ipcount",
            name="tokens_spent",
            field=models.IntegerField(default=1),
        ),
    ]
