# Generated by Django 5.2.4 on 2025-10-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_alter_employee_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
