# Generated by Django 5.2.4 on 2025-10-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
