# Generated by Django 5.2.4 on 2025-10-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0008_alter_attendance_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("leave", "Leave"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
