# Generated by Django 5.2.4 on 2025-10-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0010_alter_attendance_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
